"""Rotinas analíticas reproduzíveis dos estudos do projeto."""

from analysis.statistical_analysis import (
    COLUNAS_BASE_ESTATISTICA,
    CRITERIOS_ACEITACAO_AGRUPAMENTOS,
    INDICADORES_ATIPICIDADE,
    INDICADORES_DISTRIBUICAO,
    INTERVALO_K_AGRUPAMENTOS,
    LIMIAR_VARIANCIA_PCA,
    PARES_CORRELACAO,
    VARIAVEIS_MULTIVARIADAS,
    avaliar_agrupamentos_multivariados,
    calcular_correlacoes_spearman,
    calcular_curva_lorenz,
    calcular_estabilidade_ranking_populacional,
    calcular_influencia_correlacoes_leave_one_out,
    calcular_influencia_leave_one_out,
    calcular_medidas_concentracao,
    calcular_pca_multivariada,
    calcular_resumo_distribuicoes,
    calcular_sensibilidade_sem_sinalizadas,
    comparar_sensibilidade_escala,
    detectar_valores_atipicos,
    preparar_base_estatistica,
    preparar_base_multivariada,
    resumir_estabilidade_ranking,
    resumir_valores_atipicos,
    validar_base_estatistica,
)

__all__ = [
    "COLUNAS_BASE_ESTATISTICA",
    "CRITERIOS_ACEITACAO_AGRUPAMENTOS",
    "INDICADORES_ATIPICIDADE",
    "INDICADORES_DISTRIBUICAO",
    "INTERVALO_K_AGRUPAMENTOS",
    "LIMIAR_VARIANCIA_PCA",
    "PARES_CORRELACAO",
    "VARIAVEIS_MULTIVARIADAS",
    "avaliar_agrupamentos_multivariados",
    "calcular_correlacoes_spearman",
    "calcular_curva_lorenz",
    "calcular_estabilidade_ranking_populacional",
    "calcular_influencia_correlacoes_leave_one_out",
    "calcular_influencia_leave_one_out",
    "calcular_medidas_concentracao",
    "calcular_pca_multivariada",
    "calcular_resumo_distribuicoes",
    "calcular_sensibilidade_sem_sinalizadas",
    "comparar_sensibilidade_escala",
    "detectar_valores_atipicos",
    "preparar_base_estatistica",
    "preparar_base_multivariada",
    "resumir_estabilidade_ranking",
    "resumir_valores_atipicos",
    "validar_base_estatistica",
]
